/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * @TypeDoc(
 *     description = "行为"
 * )
 */
public enum Action implements org.apache.thrift.TEnum {
  /**
   * @FieldDoc(
   *     description = "其他"
   * )
   */
  OTHER(0),
  /**
   * @FieldDoc(
   *     description = "保护"
   * )
   */
  SHIELD(1),
  /**
   * @FieldDoc(
   *     description = "置底"
   * )
   */
  SINK(2),
  /**
   * @FieldDoc(
   *     description = "加降权,新的权重调整统一为加降权,1.0.7之前是提权"
   * )
   */
  UPGRADE(3);

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Action findByValue(int value) { 
    switch (value) {
      case 0:
        return OTHER;
      case 1:
        return SHIELD;
      case 2:
        return SINK;
      case 3:
        return UPGRADE;
      default:
        return null;
    }
  }
}
